# Generated by Django 5.0.1 on 2024-02-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='like karaj', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.PositiveIntegerField(help_text='like 3149757953'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(help_text='like Alborz', max_length=255),
        ),
    ]
