# Generated by Django 5.0.1 on 2024-02-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpcode_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpCode',
        ),
    ]
