# Generated by Django 5.0.1 on 2024-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.CharField(choices=[('not paid', 'Not Paid'), ('paid', 'Paid')], default=False, max_length=25),
        ),
    ]
