# Generated by Django 5.0.1 on 2024-02-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
