# Generated by Django 5.0.1 on 2024-02-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=10),
            preserve_default=False,
        ),
    ]
