# Generated by Django 5.0.1 on 2024-01-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_coupon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.CharField(choices=[('paid', 'Paid'), ('not paid', 'Not Paid')], default=False, max_length=25),
        ),
    ]
