# Generated by Django 5.0.1 on 2024-03-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_coupon_max_discount_order_max_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='max_discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
