# Generated by Django 5.0.1 on 2024-02-04 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_is_paid'),
        ('products', '0011_alter_category_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='city',
            field=models.CharField(blank=True, help_text='like karaj', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, help_text='like 3149757953', null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='province',
            field=models.CharField(blank=True, help_text='like Alborz', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='like DJke21x', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, help_text='like karaj', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, help_text='like 3149757953', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, help_text='like Alborz', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacions', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacions', to=settings.AUTH_USER_MODEL),
        ),
    ]
