# Generated by Django 5.0.1 on 2024-03-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_max_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='max_discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='max_discount',
        ),
    ]
