# Generated by Django 5.0.1 on 2024-02-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='products',
            new_name='product',
        ),
    ]
