# Generated by Django 5.0.1 on 2024-02-07 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kos',
            field=models.CharField(default=datetime.datetime(2024, 2, 7, 10, 17, 17, 71550, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
