# Generated by Django 5.0.1 on 2024-01-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, through='products.ProductFeatureValue', to='products.productfeature'),
        ),
    ]
