# Generated by Django 5.0.1 on 2024-02-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_kos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='kos',
        ),
    ]
