# Generated by Django 5.0.1 on 2024-01-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
