# Generated by Django 5.0.1 on 2024-02-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.AddField(
            model_name='productfeature',
            name='products',
            field=models.ManyToManyField(blank=True, through='products.ProductFeatureValue', to='products.product'),
        ),
    ]
