# Generated by Django 5.0.1 on 2024-01-31 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_discount_max_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 21, 9, 26, 237229, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
