# Generated by Django 5.0.1 on 2024-01-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_discount_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, through='products.ProductFeatureValue', to='products.productfeature'),
        ),
    ]
