# Generated by Django 5.0.1 on 2024-02-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_features_productfeature_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'brand'), 'verbose_name_plural': 'products'},
        ),
    ]
