# Generated by Django 5.0.1 on 2024-02-01 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_is_availabe_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeature',
            name='numeric_value',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='text_value',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 2, 1, 8, 27, 50, 738248, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
