# Generated by Django 5.0.1 on 2024-02-04 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.TextField(default=datetime.datetime(2024, 2, 4, 21, 37, 13, 552649, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
